### ISSUE TITLE
Create a `transfer()` function

### ISSUE THREAD

**Issue by Dprof-in-tech** [dewdrop-labs/transverse-contracts#2]
The transfer function should be able transfer USDT from one user to another user  using world id.
Write test for this function and ensure all scenarios and edge cases are covered

**Comment by Hoossayn** [comment]
Hi, will like to work on this

**Comment by 7-falseparfait** [comment]
Can I try solving this issue?

**Comment by Hoossayn** [comment]
Hi, can i take on this ?

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by KoxyG** [comment]
Hi my name is Koxy, I am a blockchain developer. I would work on this by:

1. Implementing the transfer function with World ID verification and USDT transfer logic
2. Writing tests covering:
   - Successful transfers with valid World ID proof
   - Failed transfers (invalid proof, insufficient balance)
   - Edge cases (zero transfers, decimals handling)

I can start working on this right away and deliver asap.

**Comment by blessingbytes** [comment]
i would love to work on this issue

**Comment by vestor-dev** [comment]
hey sir i would love to work on this issue 
i'm a blockchain dev and i would love to handle this issue 
assign me and i'll get to work

**Comment by Nityam573** [comment]
Can I handle this task?

**Comment by morelucks** [comment]
My name is Kamshak Lucky Isuwa, and I am excited to apply for the developer role to implement the transfer() function for transferring USDT between users using World ID. With hands-on experience in Solidity, Cairo, and blockchain development, I am confident in delivering a secure and efficient solution within 24 hours.
