### ISSUE TITLE
Create a `record_transaction_history()` function.

### ISSUE THREAD

**Issue by Dprof-in-tech** [dewdrop-labs/transverse-contracts#3]
Record every transaction that occurs in the smart contract, for a particular user.
Write test for this function and ensure all scenarios and edge cases are covered

**Comment by Birdmannn** [comment]
Hey prof in tech, I'm Pascal with experience in writing cairo-starknet smart contracts, You can check my repo. I'm a new contributor to this project and I would wish to carry out this task to further upgrade my skills. I'll read the codebase and any other files where possible to create this function, and I'll test it for all possible cases to ensure it is free from bugs. ETA < a day

**Comment by Levi-Ojukwu** [comment]
## About Me 
I am a web3 full stack developer with expertise in blockchain technology and frontend engineering. I build on EVM compatible (Solidity) and Starknet (Cairo) blockchains.
In the blockchain domain, my expertise in solidity and Cairo has enabled me to design, develop, and deploy smart contracts on the Ethereum and Starknet based platforms, facilitating decentralized applications (dApps) that are revolutionizing industries. 

## How to tackle the issue
- To tackle this issue, first I will create a function named `record_transacttion_history`.
- Then I will write a logic that will record every transaction performed by a user and.
- Then I will write the test of the function.

**Comment by zintarh** [comment]
May I be assigned to this?

**Comment by 3th-Enjay** [comment]
Is it okay if I take this?

**Comment by GideonBature** [comment]
Could I be assigned to this?

**Comment by chigozzdevv** [comment]
Could I take on this issue?

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by Belloabraham121** [comment]
Hey! I'm Iteooluwakisi.
Member of Web3Bridge. I have contributed before to other projects like:
• CoinSafe (A Defi startup built on Lisk)
• Scaffold-ETH
• BuidlGuidl
I am a frontend developer, proficient in ReactJS/NextJS, TypeScript, Solidity, and Cairo.
Can I work on this issue?
Plan to Solve the Issue:
Study the codebase to understand the current structure and functionality.
Understand the problem that needs to be solved by thoroughly reading the issue details.
Leverage all provided resources within the issue to get a better grasp of the task at hand.
If I encounter roadblocks, I will ask questions ASAP in the relevant group/chat to move forward effectively.
I will open a PR and wait for your feedback.

**Comment by Nityam573** [comment]
I’d love to work on this task.

**Comment by markdavid000** [comment]
## About Me
I’m a blockchain and frontend developer passionate about creating decentralized applications. I have hands-on experience developing smart contracts on EVM-compatible blockchains using Solidity. I focus on building secure and efficient systems while crafting intuitive user interfaces to bridge the gap between complex blockchain technology and everyday users.

## Solution Plan
- I will create a function called `record_transaction_history()`
- I will implement a logic within this function to log every user's transaction
- I will write a test to make sure the function is working perfectly

## ETA
8-9 Hours

**Comment by emmanueldindu** [comment]
Could I be assigned to this?
