### ISSUE TITLE
Create a function `get_transaction_history()`

### ISSUE THREAD

**Issue by Dprof-in-tech** [dewdrop-labs/transverse-contracts#4]
Write a function that returns all the transactions made by a user.
Write test for this function and ensure all scenarios and edge cases are covered

**Comment by Levi-Ojukwu** [comment]
## About Me 
I am a web3 full stack developer with expertise in blockchain technology and frontend engineering. I build on EVM compatible (Solidity) and Starknet (Cairo) blockchains.
In the blockchain domain, my expertise in solidity and Cairo has enabled me to design, develop, and deploy smart contracts on the Ethereum and Starknet based platforms, facilitating decentralized applications (dApps) that are revolutionizing industries. 

## How to tackle the issue
- To tackle this issue, I will start by creating a function named `get_transaction_history`, then the function will have a logic that gets the transaction histories from a mapping that returns an array.
 - Then the function will return the array from the mapping.
- Then I will write a test for the function.

###  ETA - 10 hours

**Comment by estherbreath** [comment]
I’d like to work on this, Please

Here are concise approaches I will use to implement the get_transaction_history() function.

1.   Query the blockchain for all transactions associated with the user's address. 
2. Filter and sort the transactions chronologically, excluding any that don't belong to the user. 
3. Return the sorted list of transactions, including relevant details like timestamp, hash, and transaction type.

**Comment by zintarh** [comment]
Could I take on this issue?

**Comment by 3th-Enjay** [comment]
Is it okay if I tackle this?

**Comment by emarc99** [comment]
Can I try solving this issue?

**Comment by GideonBature** [comment]
Let me handle this issue!

**Comment by chigozzdevv** [comment]
Hello, good day :)
May I be assigned to this?

**Comment by martinvibes** [comment]
i'm a frontend dev and blockchain dev 
i would love to work on this and get it done
I’m interested in this one.
kindly assign

**Comment by Naomi-Gift** [comment]
Is it okay if I tackle this?

**Comment by markdavid000** [comment]
##About Me
I’m a blockchain and frontend developer passionate about creating decentralized applications. I have hands-on experience developing smart contracts on EVM-compatible blockchains using Solidity. I focus on building secure and efficient systems while crafting intuitive user interfaces to bridge the gap between complex blockchain technology and everyday users.

## Solution Plan
I will create a function called `get_transaction_history()`, The logic of this function will :
- Access a mapping that stores transaction histories
- Retrieve the relevant array of transactions from the accessed mapping
- Return the retrieved array of transaction histories

## ETA
8-9 Hours

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by ShantelPeters** [comment]
Can I work on this, please?

**Comment by Belloabraham121** [comment]
Hey! I'm Iteooluwakisi.
Member of Web3Bridge. I have contributed before to other projects like:
• CoinSafe (A Defi startup built on Lisk)
• Scaffold-ETH
• BuidlGuidl
I am a frontend developer, proficient in ReactJS/NextJS, TypeScript, Solidity, and Cairo.
Can I work on this issue?
Plan to Solve the Issue:
Study the codebase to understand the current structure and functionality.
Understand the problem that needs to be solved by thoroughly reading the issue details.
Leverage all provided resources within the issue to get a better grasp of the task at hand.
If I encounter roadblocks, I will ask questions ASAP in the relevant group/chat to move forward effectively.
I will open a PR and wait for your feedback.

**Comment by anihdev** [comment]
Can I attempt this issue? Could I try solving this? im anih somadina experieced in writing cairo, to attemt this ill write a VIEW function `get_transaction_history` itll be able read the stotage that stores transaction, get transactions from the stored mapping and eventually Return the stored transaction histories. i will also write tests to cover edge cases. ETA 12HRS

**Comment by vestor-dev** [comment]
hey sir i would love to work on this issue 
i'm a blockchain dev and i would love to handle this issue 
assign me and i'll get to work
