### ISSUE TITLE
In-App wallet structure setup

### ISSUE THREAD

**Issue by Dprof-in-tech** [dewdrop-labs/transverse-contracts#5]
You build the in app wallet to be initialized for every user who gets on the app so they are able to recieve and transfer money.

**Comment by casweeney** [comment]
## Setting up the wallet.
- I will scaffold a solidity project with foundry using `forge` command
- I will create a smart contract with the necessary setup and functions where other contributors can build upon.

**Comment by starknetbrother** [comment]
Let me try this one!

**Comment by Naomi-Gift** [comment]
Could I be assigned to this?

**Comment by ShantelPeters** [comment]
I’m interested in this one.

**Comment by blessingbytes** [comment]
i would love to tackle this issue

**Comment by mimisavage** [comment]
Could I grab this task?

**Comment by Nityam573** [comment]
Can I work on this, please?

**Comment by emmanueldindu** [comment]
Could I take on this issue?
